### ISSUE TITLE
关于【hash -> 区块头】和【高度 -> hash】的存储记录可能出现不一致的问题的处理逻辑

### ISSUE THREAD

**Issue by chihuahuastrong** [Elements-Studio/poly#1]
在 Poly 内，【hash -> 区块头】（区块内容里面有高度字段）与【高度 -> hash】是分别存储的，这两种存储记录可能会出现不一致的情况。因为对它们的更新操作是没有数据库事务的强一致性保证的，所以**理论上这样的情况一定是有一定的概率出现**。

按照 Poly 链内之前的处理逻辑，当 Relayer 提交区块头时，会直接以 hash 查重，如果 hash 已经存在，则直接返回成功，什么都不做，包括【高度 -> hash】的存储记录也是不会更新的。

这导致在在测试过程中发生过这样的问题：Relayer 向 Poly 链提交区块头，Poly 链内的 handler 处理抛出难度校验失败，按原来的查重逻辑（在 Poly 内不修改或注释掉一些原有的代码），relayer 无法通过回滚到某一个（发生错误前的）高度然后重新提交正确的链上的数据来修复。

这个问题之前使用的方法是注释掉 Poly 内的一些代码，然后由 Relayer 重新提交正确的区块头信息去覆盖 Poly 内的错误数据的方式进行处理（也就是出现问题后需要手动干预）。但是这个方式显然不是最好的方式，我们是否可以实现（或已经实现？）出现此类问题后的程序自动修复？有待进一步确认。

**Comment by chihuahuastrong** [comment]
同步头的方法 SyncBlockHeader 见：

https://github.com/Elements-Studio/poly/blob/828a835c39e809649bae1e64bd7357c2fb281c90/native/service/header_sync/starcoin/header_sync.go#L68

这个方法执行的几个步骤：

1. 调用 IsHeaderExist 判断 relayer 传入的区块头是否已经存在。“已存在”的标准是【hash -> 区块头】的记录在 poly 内是否已经存储。
2. 通过 GetHeaderByHash 获取传入区块头的父区块头，进行难度校验等等操作。
3. 调用 putBlockHeader 存储传入区块的【hash -> 区块头】的记录。
4. 调用 putBlockInfo 存储【blockId -> BlockInfo】的记录（这些信息是为了支持难度校验。以太坊的 head sync handler 没有这一步）。
5. 如果在 poly 内保存的 starcoin **链的当前（最大）高度**对应的区块 hash 等于传入区块的“父区块”的 hash，则认为 starcoin 链在正常增长（不需要 ReStructChain），调用 appendHeader2Main 方法。在 appendHeader2Main 方法内，会更新传入区块的【高度 -> hash】记录。

由于 poly 内对存储的更新没有数据库事务的强一致性保证，所以**无法保证在上面的第 3 步调用成功后**，**后面**存储【blockId -> BlockInfo】记录以及存储【高度 -> hash】记录**的操作也一定能成功**。加上多个 relayer 可能会并发同步区块头过来，貌似也不能保证【hash -> 区块头】与【高度 -> hash】之间“强一致”（关于它们与【blockId -> BlockInfo】的一致性问题先不论）。

如果 realyer 同步过来的区块的【hash -> 区块头】的记录已存在，在上面的操作的第 1 步就已经直接退出 SyncBlockHeader 的执行。那么当【hash -> 区块头】和其他存储记录出现不一致时，这个不一致会导致后面新进入的区块的难度校验失败，于是错误再也没法“更正”过来，这可能会堵塞后面所有区块头的同步。

目测以太坊的那个 header sync handler 应该也存在类似的数据一致性问题。但是对于**以太坊**来说，发生这样的导致的后果远没有 starcoin 严重，因为它对 eth-relayer 同步过来的区块头做难度校验的时候，并**不依赖 GetHeaderByHeight 方法**，只是通过传入区块的 ParentHash 去取父区块头信息。

而 starcoin 这边的情况是，我们要多次调用 GetHeaderByHeight 来进行难度计算，调用次数取决于 difficulty window 的大小（当前可能是 24），多次调用也增大了出问题的概率。

**Comment by wubuku** [comment]
改进方法是否可以考虑：

* 改进 IsHeaderExist 的实现？增加更多的判断（不只是判断【hash -> 区块头】的记录是否存在）？
* 难度校验是否可以不依赖 GetHeaderByHeight？而是通过 ParentHash 去取 difficulty window 个区块头？

**Comment by jolestar** [comment]
1. 是不是 IsHeaderExist 同时判断 hash-> 区块头 和 高度 -> Hash? 只要一个不匹配就继续重新处理一下。
2. 难度校验可以不依赖 GetHeaderByHeight， 可以根据 ParentHash 向前遍历。

**Comment by ssyuan** [comment]
1、是解决第三步成功而第5步没有成功的情况，其实就是保证 hash->header  height->hash完全一致；这一个解决好了，第二个问题就不存在了
2、第二问题建议不需要改，我理解拿高度取正是因为假设第五步正常执行了，而拿hash只能是第三步正常执行。如果只改这一处，那证明验证的逻辑还有其他地方都同理需要改了吧。
所以重点是解决第一问题。
 直接把 IsHeaderExist 的 **continue**删掉，重新执行一遍（后面的逻辑是可重入的）；还是做完整的一致性检查，但其实后面的blockinfo和current height都需要保持一致的

**Comment by chihuahuastrong** [comment]
“直接把 IsHeaderExist 的 continue删掉，重新执行一遍（后面的逻辑是可重入的）”，这个 poly 的伙伴不推荐，有说过这么做的问题。

**Comment by siovanus** [comment]
1.首先这个不一致问题应该只会在有bug的情况下出现吧，正常运行时应该不会出现这个问题吧？
2.如果正常运行不会出现问题那么就是需要有个修复错误区块的功能，但是由于relayer可能是别人恶意的，因此这个修复功能可能也会被恶意调用。
3.我觉得有两种方法，第一种是中心化的去修复，也就是和init genesis一样，必须由poly调用（三分之二的共识节点签名），此时poly可以修改任何一个区块。第二种是要在链上证明这个修改是正确的，也就是修改之后的难度更大。
4.在同步区块头的逻辑上做应该是不合适的，这其实是又把区块弄回了更低的高度，那任何人都可以一直回滚。所以还是另外加一个区块修复方法。

**Comment by jolestar** [comment]
再次确认了一下，按现在的校验逻辑，后面有 total difficulty 校验机制，是不会出现回滚到更低的难度的，也不会被用来攻击。考虑的情况应该是：节点处理到中途挂掉，height -> hash 这个映射表没有写进去，然后导致后面的验证都无法正常进行的问题。


> 1.首先这个不一致问题应该只会在有bug的情况下出现吧，正常运行时应该不会出现这个问题吧？ 2.如果正常运行不会出现问题那么就是需要有个修复错误区块的功能，但是由于relayer可能是别人恶意的，因此这个修复功能可能也会被恶意调用。 3.我觉得有两种方法，第一种是中心化的去修复，也就是和init genesis一样，必须由poly调用（三分之二的共识节点签名），此时poly可以修改任何一个区块。第二种是要在链上证明这个修改是正确的，也就是修改之后的难度更大。 4.在同步区块头的逻辑上做应该是不合适的，这其实是又把区块弄回了更低的高度，那任何人都可以一直回滚。所以还是另外加一个区块修复方法。

**Comment by jolestar** [comment]
https://github.com/Elements-Studio/poly/blob/dev/native/service/header_sync/starcoin/header_sync.go

这个分支里， 应该少了一个 BlockInfo 的校验。 BlockInfo 的 total_difficulty 要通过 parent BlockInfo 的 total_difficulty  + header.difficulty 进行校验一下。不然别人可以伪造一个 BlockInfo 来欺骗。

**Comment by chihuahuastrong** [comment]
我觉得可以多个修改方案并行：

1. “难度校验可以不依赖 GetHeaderByHeight， 可以根据 ParentHash 向前遍历”这个做法如果可行，我觉得可以考虑用上。依赖越多，越容易出问题。

2. 三个存储感觉增加了因为一致性导致问题发生的几率。所以，我觉得还可以考虑 blockheader 和 blockInfo作为一个聚合一起存储。然后仿照 eth 的方案，通过 parent hash 来获取前面的区块信息。

这么改的话，就已经和 eth 的做法很相似了，毕竟这种做法也是 poly 链中一直在跑的逻辑，感觉会稳妥一些。

**Comment by chihuahuastrong** [comment]
难度校验可以不依赖 GetHeaderByHeight， 可以根据 ParentHash 向前遍历，已修改，见：

https://github.com/Elements-Studio/poly/commit/9cde7f3b1948953147000ac14d3959cbc405544a

将 blockheader 和 blockInfo 作为一个聚合一起存储，已修改，见：

https://github.com/Elements-Studio/poly/commit/57cfc079dafe85dd94d6e9f25737a184a2ad879a

**Comment by chihuahuastrong** [comment]
“BlockInfo 的 total_difficulty 要通过 parent BlockInfo 的 total_difficulty  + header.difficulty 进行校验一下”，修改见：

https://github.com/Elements-Studio/poly/commit/ae3890f7cefcb4667d6c3743af6866078e155665

在 putBlockHeader（and BlockInfo）之前加入检查逻辑，代码 ：

```go
// //////////////////////////////
headerDifficulty := new(uint256.Int).SetBytes(header.BlockHeader.Difficulty[:])
blockTotalDifficulty := new(uint256.Int).SetBytes(header.BlockInfo.TotalDifficulty[:])
parentTotalDifficulty := new(uint256.Int).SetBytes(parentHeader.BlockInfo.TotalDifficulty[:])
if blockTotalDifficulty.Cmp(new(uint256.Int).Add(parentTotalDifficulty, headerDifficulty)) != 0 {
	return errors.Errorf("SyncBlockHeader, verify difficulty error. blockTotalDifficulty:%d, parentTotalDifficulty:%d, headerDifficulty:%d", blockTotalDifficulty, parentTotalDifficulty, headerDifficulty)
}
// //////////////////////////////
//block header storage
err = putBlockHeader(native, header, headerParams.ChainID)
```

**Comment by chihuahuastrong** [comment]
Starcoin handler 目前的重组链的触发逻辑：

```go
	if currentTotalDifficulty.Cmp(parentTotalDifficulty) > 0 {
		ReStructChain(native, currentHeader, &header, headerParams.ChainID)
	}
```

如果 **“当前”总难度** 大于传入区块的 **父区块的总难度**，则……

Eth handler 的触发逻辑：

```go
	if hederDifficultySum.Cmp(currentDifficultySum) > 0 {
		RestructChain(native, currentHeader, &header, headerParams.ChainID)
	}
```

如果传入**区块的难度和** 大于 **“当前”难度和** ，则……

两者逻辑好像有差异。我们的做法是不是也没有问题？也就是说我们是不是有必要改为：传入区块的难度加上其 **父区块的总难度** 大于 **“当前”总难度** ，则触发链重组？

**Comment by jolestar** [comment]
> Starcoin handler 目前的重组链的触发逻辑：
> 
> ```go
> 	if currentTotalDifficulty.Cmp(parentTotalDifficulty) > 0 {
> 		ReStructChain(native, currentHeader, &header, headerParams.ChainID)
> 	}
> ```
> 
> 如果 **“当前”总难度** 大于传入区块的 **父区块的总难度**，则……
> 
> Eth handler 的触发逻辑：
> 
> ```go
> 	if hederDifficultySum.Cmp(currentDifficultySum) > 0 {
> 		RestructChain(native, currentHeader, &header, headerParams.ChainID)
> 	}
> ```
> 
> 如果传入**区块的难度和** 大于 **“当前”难度和** ，则……
> 
> 两者逻辑好像有差异。我们的做法是不是也没有问题？也就是说我们是不是有必要改为：传入区块的难度加上其 **父区块的总难度** 大于 **“当前”总难度** ，则触发链重组？

现在的逻辑有问题，需要改为：传入区块的难度加上其 父区块的总难度 大于 “当前”总难度。

另外 BlockInfo 的校验逻辑感觉应该迁移到:

```go
if bytes.Equal(*currentHeaderHash, header.BlockHeader.ParentHash) {
   //这里校验 BlockInfo
}
```

因为必须保证参数传递过来的区块的 parent 是 currentHeaderHash， 那个校验逻辑才有意义， 否则就需要检测总难度，检查是否要触发重组，BlockInfo 的校验逻辑会包含在重组逻辑中（重组后校验 total_difficulty).

**Comment by chihuahuastrong** [comment]
> 另外 BlockInfo 的校验逻辑感觉应该迁移到:
> 
> ```go
> if bytes.Equal(*currentHeaderHash, header.BlockHeader.ParentHash) {
>    //这里校验 BlockInfo
> }
> ```

修改见：

https://github.com/Elements-Studio/poly/commit/d361efc31940fd3f987968b60b59a642af600acd
 
> 否则就需要检测总难度，检查是否要触发重组，BlockInfo 的校验逻辑会包含在重组逻辑中（重组后校验 total_difficulty).

“重组后校验 total_difficulty”，好像现在已有的代码没有这个逻辑？这个还需要进一步修改？

**Comment by jolestar** [comment]
https://github.com/Elements-Studio/poly/commit/d361efc31940fd3f987968b60b59a642af600acd#r62498048

那重组的逻辑也需要重构一下。重组就是要从共同祖先开始，重新累加校验难度。

**Comment by jolestar** [comment]
另外感觉是不是弄个 pr review 比较方便。

**Comment by chihuahuastrong** [comment]
> [d361efc#r62498048](https://github.com/Elements-Studio/poly/commit/d361efc31940fd3f987968b60b59a642af600acd#r62498048)
> 
> 那重组的逻辑也需要重构一下。重组就是要从共同祖先开始，重新累加校验难度。

在 ReStructChain 方法中增加了校验。对 `blockTotalDifficulty.Cmp(new(uint256.Int).Add(parentTotalDifficulty, headerDifficulty))`  的校验挪到了方法 verifyTotalDifficulty 中。修改见：

https://github.com/Elements-Studio/poly/commit/66bf0c64fca5d6325bc068a0e1d84653e1796fdf

但是感觉像原来那样在保存 BlockHeader（and BlockInfo）的方法，这个地方：

https://github.com/Elements-Studio/poly/blob/66bf0c64fca5d6325bc068a0e1d84653e1796fdf/native/service/header_sync/starcoin/header_sync.go#L205

之前做检查好像也够了？因为 ReStructChain 也是从这个存储里面取信息的。

**Comment by chihuahuastrong** [comment]
> 另外感觉是不是弄个 pr review 比较方便。

在当前 Poly 的 dev 分支上提交的 PR（包括了这两天的修改）：

https://github.com/polynetwork/poly/pull/99

**Comment by chihuahuastrong** [comment]
添加了 ReStructChain 的单元测试。

https://github.com/polynetwork/poly/pull/99/commits/e2d67f9a53bf82f56e181e835fe5a5da4d5fe1ad
